version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/honda-bot-v2
permissions:
  - object: /home/ec2-user/honda-bot-v2
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: /home/ec2-user/honda-bot-v2/scripts/ApplicationStop.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: ec2-user
